import type { AugmentDefinition } from "./types";

export const AUGMENT_TIER_WEIGHTS = {
  silver: 55,
  gold: 28,
  prism: 13,
  transcendent: 4,
} as const;

export const AUGMENTS: readonly AugmentDefinition[] = [
  {
    id: "S001",
    tier: "silver",
    category: "piece",
    name: "돌격 앞으로!",
    description: "자신의 폰은 앞으로 2칸 이동할 수 있습니다.",
  },
  {
    id: "S002",
    tier: "silver",
    category: "piece",
    name: "기사의 맹격",
    description: "기존 나이트 이동에 전방 추가 1칸 이동 능력을 얻습니다.",
  },
  {
    id: "S003",
    tier: "silver",
    category: "piece",
    name: "길을 비켜라",
    description: "앞을 막는 아군 폰을 뛰어넘어 한 칸 더 전진할 수 있습니다.",
  },
  {
    id: "S004",
    tier: "silver",
    category: "piece",
    name: "첫 수의 특권",
    description: "게임 시작 후 첫 번째 폰 이동에 한해 최대 3칸 전진할 수 있습니다.",
  },
  {
    id: "S005",
    tier: "silver",
    category: "utility",
    name: "나이트 훈련소",
    description: "나이트가 한 번 더 이동할 수 있는 특수 행동권을 획득합니다.",
  },
  {
    id: "S006",
    tier: "silver",
    category: "utility",
    name: "희생의 대가",
    description: "자신의 기물이 파괴되면 다음 자신의 턴 동안 모든 기물의 이동거리가 +1 됩니다.",
  },
  {
    id: "G001",
    tier: "gold",
    category: "piece",
    name: "백발백중 저격수",
    description: "비숍의 대각선 경로에 있는 적 폰을 이동 없이 저격합니다. 게임당 2회.",
  },
  {
    id: "G002",
    tier: "gold",
    category: "piece",
    name: "이세계에 떨어진 용사",
    description: "자신의 나이트가 1개만 남으면 기존 나이트에 룩과 비숍의 이동 능력을 추가합니다.",
  },
  {
    id: "G003",
    tier: "gold",
    category: "field",
    name: "폭탄병 출몰",
    description: "자신의 폰이 파괴되면 주변 상하좌우 4칸의 모든 기물을 파괴합니다. 연쇄 폭발은 없습니다.",
  },
  {
    id: "G004",
    tier: "gold",
    category: "field",
    name: "성스러운 결계",
    description: "중앙 4칸 중 한 곳에 결계를 만들고 그 안의 아군 기물을 3턴 동안 보호합니다.",
  },
  {
    id: "G005",
    tier: "gold",
    category: "utility",
    name: "록 더 시즈탱크",
    description: "룩은 이동할 수 없지만 룩의 이동 범위에 있는 아군 기물이 룩의 이동 능력을 얻습니다.",
  },
  {
    id: "G006",
    tier: "gold",
    category: "utility",
    name: "홀로 남은 왕, 긴급탈출",
    description: "킹을 제외한 모든 기물이 사라지면 무승부가 됩니다. 체크메이트가 먼저 성립하면 패배합니다.",
  },
  {
    id: "G007",
    tier: "gold",
    category: "utility",
    name: "위장술",
    description: "킹을 제외한 자신의 모든 기물이 상대 화면에서 폰으로 보입니다. 첫 이동 시 정체가 드러납니다.",
  },
  {
    id: "P001",
    tier: "prism",
    category: "piece",
    name: "말굽의 질주",
    description: "나이트 이동 경로에 있는 상대 기물을 짓밟아 파괴합니다. 현재 규칙은 경로상의 폰 파괴부터 적용합니다.",
  },
  {
    id: "P002",
    tier: "prism",
    category: "piece",
    name: "비숍 더 레전드",
    description: "비숍은 이동할 수 없고 주변 상하좌우 4칸에 일반 폰을 생성합니다.",
  },
  {
    id: "P003",
    tier: "prism",
    category: "field",
    name: "황금향의 엘도라도",
    description: "증강 획득 시 킹 주변 8칸과 킹의 칸에 있던 아군 기물에 영구 황금 효과를 부여합니다. 황금 기물은 이동거리가 +1 됩니다.",
  },
  {
    id: "P004",
    tier: "prism",
    category: "field",
    name: "차원 이동 포탈",
    description: "원하는 두 칸을 연결합니다. 한쪽 칸에 기물이 도착하면 다른 연결 칸으로 즉시 스위치됩니다.",
  },
  {
    id: "P005",
    tier: "prism",
    category: "utility",
    name: "남자는 자신의 여자를 지키는 법",
    description: "킹이 죽어도 패배하지 않습니다. 퀸이 사라지면 패배하며 킹은 나이트 이동도 얻습니다.",
  },
  {
    id: "P006",
    tier: "prism",
    category: "utility",
    name: "운명의 데칼코마니",
    description: "공격으로 적 기물을 제거하면 즉시 추가 행동을 얻습니다. 한 턴에 추가 행동은 최대 1회입니다.",
  },
  {
    id: "T001",
    tier: "transcendent",
    category: "piece",
    name: "마법공학의 힘, 어 이게임이 아닌데",
    description: "자신의 모든 폰은 한 턴에 2번 이동할 수 있습니다.",
  },
  {
    id: "T002",
    tier: "transcendent",
    category: "piece",
    name: "여왕의 호위무사",
    description: "증강 획득 순간 퀸 주변 1칸의 아군 기물에게 1회 공격을 막는 보호막을 부여합니다.",
  },
  {
    id: "T003",
    tier: "transcendent",
    category: "field",
    name: "침몰한 도시 아틀란티스",
    description: "자신의 폰이 상대 마지막 줄에 도착하면 폰을 파괴하고 킹과 퀸을 제외한 상대 기물 하나를 파괴합니다.",
  },
  {
    id: "T004",
    tier: "transcendent",
    category: "field",
    name: "체스판 역전 세계",
    description: "보류 중인 증강. 체스판 전체를 중앙 기준 180도 대칭시키는 효과입니다.",
  },
  {
    id: "T005",
    tier: "transcendent",
    category: "utility",
    name: "킹 오브 킹",
    description: "킹이 퀸, 룩, 비숍, 나이트를 포함한 모든 기물의 이동 능력을 얻습니다.",
  },
  {
    id: "T006",
    tier: "transcendent",
    category: "utility",
    name: "협상 결렬: 왕의 귀환",
    description: "체크메이트로 죽게 되는 순간 게임당 1회 발동하여 킹을 구석으로 이동시키고 주변 8칸의 적 기물을 파괴합니다.",
  },
  {
    id: "T007",
    tier: "transcendent",
    category: "utility",
    name: "대격변",
    description: "킹을 제외한 자신의 모든 기물을 폰, 나이트, 비숍, 룩, 퀸 중 무작위 기물로 즉시 변신시킵니다.",
  },
];

export function getAugment(id: AugmentDefinition["id"]) {
  return AUGMENTS.find((augment) => augment.id === id);
}
